
std_msgs/Header header
#   uint32 seq
#   time stamp
#   string frame_id
# geometry_msgs/PoseStamped[] poses #由一系列点组成的数组 
# global_way[] poses
# global_way/Pose pose
#   global_way/Point position
    float64 x
    float64 y
    float64 k
    float64 heading

# std_msgs/Header header
#   uint32 seq
#   time stamp
#   string frame_id
# geometry_msgs/Pose pose
  # geometry_msgs/Point position
    # float64 x
    # float64 y
    # float64 z
  # geometry_msgs/Quaternion orientation
  #   float64 x
  #   float64 y
  #   float64 z
  #   float64 w

# float64 x
# float64 y
# float64 k
# float64 heading
