// Generated by gencpp from file motion_capture/nokovStamped.msg
// DO NOT EDIT!


#ifndef MOTION_CAPTURE_MESSAGE_NOKOVSTAMPED_H
#define MOTION_CAPTURE_MESSAGE_NOKOVSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace motion_capture
{
template <class ContainerAllocator>
struct nokovStamped_
{
  typedef nokovStamped_<ContainerAllocator> Type;

  nokovStamped_()
    : header()
    , pose3d()
    , pose2d()
    , acc_linear()
    , vel_linear()
    , vel_theta(0.0)
    , yaw_omega(0.0)  {
    }
  nokovStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose3d(_alloc)
    , pose2d(_alloc)
    , acc_linear(_alloc)
    , vel_linear(_alloc)
    , vel_theta(0.0)
    , yaw_omega(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose3d_type;
  _pose3d_type pose3d;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose2d_type;
  _pose2d_type pose2d;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _acc_linear_type;
  _acc_linear_type acc_linear;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _vel_linear_type;
  _vel_linear_type vel_linear;

   typedef double _vel_theta_type;
  _vel_theta_type vel_theta;

   typedef double _yaw_omega_type;
  _yaw_omega_type yaw_omega;





  typedef boost::shared_ptr< ::motion_capture::nokovStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_capture::nokovStamped_<ContainerAllocator> const> ConstPtr;

}; // struct nokovStamped_

typedef ::motion_capture::nokovStamped_<std::allocator<void> > nokovStamped;

typedef boost::shared_ptr< ::motion_capture::nokovStamped > nokovStampedPtr;
typedef boost::shared_ptr< ::motion_capture::nokovStamped const> nokovStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_capture::nokovStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_capture::nokovStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_capture::nokovStamped_<ContainerAllocator1> & lhs, const ::motion_capture::nokovStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose3d == rhs.pose3d &&
    lhs.pose2d == rhs.pose2d &&
    lhs.acc_linear == rhs.acc_linear &&
    lhs.vel_linear == rhs.vel_linear &&
    lhs.vel_theta == rhs.vel_theta &&
    lhs.yaw_omega == rhs.yaw_omega;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_capture::nokovStamped_<ContainerAllocator1> & lhs, const ::motion_capture::nokovStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_capture

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motion_capture::nokovStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_capture::nokovStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_capture::nokovStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_capture::nokovStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_capture::nokovStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_capture::nokovStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_capture::nokovStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c50287cd23c009f37db021e9ac09647";
  }

  static const char* value(const ::motion_capture::nokovStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c50287cd23c009fULL;
  static const uint64_t static_value2 = 0x37db021e9ac09647ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_capture::nokovStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_capture/nokovStamped";
  }

  static const char* value(const ::motion_capture::nokovStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_capture::nokovStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Pose pose3d\n"
"geometry_msgs/Pose2D pose2d\n"
"geometry_msgs/Vector3 acc_linear\n"
"geometry_msgs/Vector3 vel_linear\n"
"float64 vel_theta\n"
"float64 yaw_omega\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::motion_capture::nokovStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_capture::nokovStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose3d);
      stream.next(m.pose2d);
      stream.next(m.acc_linear);
      stream.next(m.vel_linear);
      stream.next(m.vel_theta);
      stream.next(m.yaw_omega);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nokovStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_capture::nokovStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_capture::nokovStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose3d: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose3d);
    s << indent << "pose2d: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose2d);
    s << indent << "acc_linear: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.acc_linear);
    s << indent << "vel_linear: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.vel_linear);
    s << indent << "vel_theta: ";
    Printer<double>::stream(s, indent + "  ", v.vel_theta);
    s << indent << "yaw_omega: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_omega);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_CAPTURE_MESSAGE_NOKOVSTAMPED_H
